### PR TITLE
Fix to compile with Visual C++ 2015

### PR DESCRIPTION
**Pull request by egtra**
Some fixes for Visual C++ 2015.

- Add `#undef environ`. Because `environ` is defined `(*__p__environ())` in `<stdlib.h>`.
- Remove `snprintf` macro. Visual C++ 2015 has `snprintf`.
- Remove `ECONNRESET` macro. This is copy from `libtelnet-proxy.c` to `libtelnet-chatd.c`.

### CODE REVIEW

**Comment by thefallentree** [comment]
cool

**Comment by seanmiddleditch** [comment]
I'm against the changing from Unicode to Multibyte. The latter should be considered deprecated.

I'm also unsure about the conditions that were added for the macros. The compiler version is not directly related to the stdlib version, e.g. you can use mingw to compile using Microsoft's headers.

**Comment by egtra** [comment]
Thank you for response. I agree it.

But condition for `#define snprintf _snprintf` is needed for Visual C++ 2015. Because Visual C++ 2015 generates following compile error if there is `#define snprintf _snprintf`.

`
1>c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration
`

> e.g. you can use mingw to compile using Microsoft's headers.

Therefore I use `_UCRT` instead `_MSC_VER` for condition.

**Comment by seanmiddleditch** [comment]
Looks much better. I forgot to ask the first time: could you please rebase this onto the develop branch? Thanks!

**Comment by egtra** [comment]
Sure. I rebased it. Thank you too!

**Pull request merged**
