### PR TITLE
Minor fix

### PR DESCRIPTION
**Pull request by xiaoxiang781216**

### CODE REVIEW

**Comment by thefallentree** [comment]
Thanks for the PR,  However it has been awhile since there is action on this repo if you can send them to an unofficial mirror I made : https://github.com/fluffos/libtelnet I would happy to merge this.

**Comment by xiaoxiang781216** [comment]
@thefallentree seem you already cherry-pick the patchset:
https://github.com/fluffos/libtelnet/pull/1

**Comment by seanmiddleditch** [comment]
@xiaoxiang781216 This looks a little bit more than a "minor" fix, which is awesome! :)

Can you give a little detail on the changes (some look fairly serious, even), and add yourself to the `AUTHORS` file? Thanks!

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 This looks a little bit more than a "minor" fix, which is awesome! :)
> 
> Can you give a little detail on the changes (some look fairly serious, even), and add yourself to the `AUTHORS` file? Thanks!

I think the most patch is trivial fix, just the second patch need more explanation:
1.Remove NEGOTIATE_EVENT at line 410 and 468, because the state doesn't really change from user perspective.
2.Notify user with TELNET_EV_DONT at line 494, since our state change should notify with DO/DONT, not WILL/WONT.
3.It's wrong to notify user TELNET_EV_WILL at line 499, since the real state change to NO temporarily.
4.We should send the pending DO request at line 440, since their real state changed to NO  temporarily, the notification should be TELNET_EV_WONT.

**Review by seanmiddleditch — APPROVED** [review]

**Comment by jtenner** [comment]
I'll have to make sure I copy this changes downstream!

**Pull request merged**
